server {
  listen 127.0.0.1:8080;
  server_name art.lmtool.online;

  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  server_name art.lmtool.online;

  ssl_certificate /etc/nginx/ssl/art.lmtool.online_bundle.pem;
  ssl_certificate_key /etc/nginx/ssl/art.lmtool.online.key;
  ssl_session_timeout 1d;
  ssl_session_cache shared:FluxArtSSL:10m;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  client_max_body_size 25m;

  location /assets-store/ {
    rewrite ^/assets-store/(.*)$ /fluxart-assets/$1 break;
    proxy_pass http://127.0.0.1:9000;
    proxy_http_version 1.1;
    proxy_set_header Host 127.0.0.1:9000;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location / {
    proxy_pass http://127.0.0.1:3207;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
